# SPDX-License-Identifier: GPL-3.0-or-later
from typing import Any
class DBusException(Exception): ...
def SystemBus() -> Any: ...
def SessionBus() -> Any: ...
def Interface(bus_object: Any, dbus_interface: str) -> Any: ...
def Boolean(value: bool) -> bool: ...
def String(value: str) -> str: ...
def Int32(value: int) -> int: ...
