# SPDX-License-Identifier: GPL-3.0-or-later
from typing import Any, Callable, TypeVar
F = TypeVar('F', bound=Callable[..., Any])
class BusName:
    def __init__(self, name: str, bus: Any) -> None: ...
class Object:
    def __init__(self, bus_name: BusName, object_path: str) -> None: ...
def method(dbus_interface: str, in_signature: str = ..., out_signature: str = ..., sender_keyword: str = ...) -> Callable[[F], F]: ...
def signal(dbus_interface: str, signature: str = ...) -> Callable[[F], F]: ...
